Use Copier for project generation

diff --git a/.github/workflows/rename-project.yml b/.github/workflows/rename-project.yml
--- a/.github/workflows/rename-project.yml
+++ b/.github/workflows/rename-project.yml
@@ -43,11 +43,9 @@ jobs:
         uses: actions/github-script@v7
         with:
           script: |
-            const repoName = context.repo.repo.replace(/-/g, '_').toLowerCase();
-            const repoUrlName = context.repo.repo;
+            const repoName = context.repo.repo;
             const repoOwner = context.repo.owner;
             core.exportVariable('REPOSITORY_NAME', repoName);
-            core.exportVariable('REPOSITORY_URLNAME', repoUrlName);
             core.exportVariable('REPOSITORY_OWNER', repoOwner);
 
             const repo = await github.rest.repos.get({
@@ -56,65 +54,69 @@ jobs:
             });
             const description = repo.data.description;
             const visibility = repo.data.visibility;
-            const isPublic = visibility === 'public';
 
             core.exportVariable('REPOSITORY_DESCRIPTION', description);
-            core.exportVariable('is_public', isPublic);
+            core.exportVariable('REPOSITORY_VISIBILITY', visibility);
 
       - name: Rename Repository Check
         if: env.is_template == 'false'
         run: |
-          echo "needs_renaming=$(ls .github/template.yml &> /dev/null && echo true || echo false)" >> "$GITHUB_ENV"
+          echo "needs_renaming=$(ls .github/workflows/rename-project.yml &> /dev/null && echo true || echo false)" >> "$GITHUB_ENV"
 
-      - name: Rename project-README.md to README.md
+      - name: Install Poetry
+        if: env.is_template == 'false' && env.needs_renaming == 'true'
+        uses: snok/install-poetry@v1
+        with:
+          version: 1.7.1
+          virtualenvs-create: true
+          virtualenvs-in-project: false
+
+      - name: Set up Python
+        if: env.is_template == 'false' && env.needs_renaming == 'true'
+        uses: actions/setup-python@v5
+        with:
+          python-version-file: .python-version
+          cache: poetry
+
+      - name: Install dependencies
         if: env.is_template == 'false' && env.needs_renaming == 'true'
         run: |
-          mv project-README.md README.md
-
-      - name: Add markdown-link-check Config File
-        if: env.is_template == 'false' && env.needs_renaming == 'true'
-        run: |
-          file=".github/linters/.markdown-link-check.json"
-          mv -f .github/linters/.project-markdown-link-check.json "$file"
-
-          if [ "$is_public" = false ]; then
-            new_pattern='{
-              "pattern": "author_name/project_urlname",
-              "reason": "Private repository"
-            }'
-            existing_patterns=$(jq '.ignorePatterns' "$file")
-            if [ "$existing_patterns" = "null" ]; then
-              jq '.ignorePatterns = [] | .ignorePatterns += [ '"$new_pattern"' ]' "$file" > tmpfile && mv tmpfile "$file"
-            else
-              jq '.ignorePatterns += [ '"$new_pattern"' ]' "$file" > tmpfile && mv tmpfile "$file"
-            fi
-          fi
+          make install
 
       - name: Rename the Project
         if: env.is_template == 'false' && env.needs_renaming == 'true'
         run: |
-          echo "Renaming the project with -a(author) ${{ env.REPOSITORY_OWNER }} -n(name) ${{ env.REPOSITORY_NAME }} \
-            -u(urlname) ${{ env.REPOSITORY_URLNAME }} \
-            -d(description) ${{ env.REPOSITORY_DESCRIPTION || env.REPOSITORY_URLNAME }}"
+          # Create a temporary directory
+          temp_dir=$(mktemp -d)
 
-          .github/rename_project.sh -a ${{ env.REPOSITORY_OWNER }} -n ${{ env.REPOSITORY_NAME }} \
-            -u ${{ env.REPOSITORY_URLNAME }} -d "${{ env.REPOSITORY_DESCRIPTION || env.REPOSITORY_URLNAME }}"
+          # Move .git directory to the temporary directory
+          mv .git "$temp_dir/"
 
-      - name: Remove CodeQL Workflow
-        if: env.is_template == 'false' && env.needs_renaming == 'true' && env.is_public == 'false'
-        run: |
-          rm ".github/workflows/codeql.yml"
-          # Remove the CodeQL badge from the README
-          sed -i '/\[!\[Build Status\].*codeql\.yml.*\]/d' README.md
+          # Run copier
+          poetry run copier copy "$(pwd)" "$temp_dir" --trust --force --quiet \
+            --data "repository_name=${{ env.REPOSITORY_NAME }}" \
+            --data "repository_description=${{ env.REPOSITORY_DESCRIPTION || env.REPOSITORY_NAME }}" \
+            --data "repository_owner=${{ env.REPOSITORY_OWNER }}" \
+            --data "repository_visibility=${{ env.REPOSITORY_VISIBILITY }}" \
+            --data "is_running_in_github_actions=true"
+
+          # Remove existing files and directories from the current directory including hidden files
+          shopt -s dotglob
+          rm -rf ./*
+
+          # Move contents from temporary directory to the current directory
+          mv -f "$temp_dir"/* .
+
+          # Clean up temporary directory
+          rm -rf "$temp_dir"
 
       - name: Cleanup
         if: env.is_template == 'false' && env.needs_renaming == 'true'
         run: |
-          rm .github/rename_project.sh
           rm .github/workflows/rename-project.yml
 
       - uses: stefanzweifel/git-auto-commit-action@v5
-        if: env.is_template == 'false'
+        if: env.is_template == 'false' && env.needs_renaming == 'true'
         with:
-          commit_message: ✅ Ready to clone and use
+          commit_message: ✅ Ready to clone
           push_options: --force
